
version: '3.3'
services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb-util-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data